apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vd2a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vd2a
    app.kubernetes.io/part-of: load-app-865a9ab7-3958-4f62-bd3f-824c7e9d1bb0
  name: devfile-sample-vd2a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vd2a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vd2a
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-97-tenant/load-app-865a9ab7-3958-4f62-bd3f-824c7e9d1bb0/devfile-sample-vd2a@sha256:4789c231a64985bec6aa983ad38d0a6e6ae90dead6f182f78e6f198af5ef964e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
